list: $/mel/secondplugin/models/book/columns.yaml
modelClass: Mel\Secondplugin\Models\Book
title: Books
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'mel/secondplugin/books/update/:id'
